import java.util.ArrayList;

/**
 * Attempts to evaluate how difficult a board is based on how many irrelevant
 * cars are on the board. An irrelevant car is one that is never moved. Since
 * there might be different numbers of irrelevant cars for each solve path, we
 * will take the minimum of all possible paths.
 *
 * The idea behind this is that the less different cars one has to move, the
 * easier it is to find a solution since the puzzle is smaller in a sense.
 */
public class IrrelevancyEvaluator implements Evaluator {
    // TODO: GO THROUGH ALL PATHS
    // currently only looks at the solve path generated by Solver
    /**
     * Returns the score using this evaluation method.
     * @param b the board to evaluate
     * @return the score
     */
    public double eval(Board b) {
        // note thae booleans initialize as false
        boolean[] wasUsed = new boolean[b.getCars().size()];
        for (int i = 0; i < wasUsed.length; i++) {
            wasUsed[i] = false;
        }
        ArrayList<Move> moves = Solver.solveBoardWithMoves(b);

        // turns index i of the wasUsed to true if the car at index i was moved
        for (int j = 0; j < moves.size(); j++) {
            wasUsed[moves.get(j).index] = true;
        }

        // counts all the falses in wasUsed
        double score = 0;
        for (int i = 0; i < wasUsed.length; i++) {
            if (!wasUsed[i]) {
                score++;
            }
        }
        return score;
    }

    /*public int getScore(Board b) {
        return eval(b);
    }*/
}
